#!/usr/bin/perl -w

while(<>){
 s:(emb\" Pron) ([S|P]):$1 Det $2:g;
 s:(enda\" Pron) ([S|P]):$1 Pos Refl $2:g;
 s:(enese\" Pron) ([S|P]):$1 Pos Refl $2:g;
 s:(eikeegi\" Pron) ([S|P]):$1 Indef $2:g;
 s:(eimiski\" Pron) ([S|P]):$1 Indef $2:g;
 s:(emb-kumb\" Pron) ([S|P]):$1 Det $2:g;
 s:(esimene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(iga\" Pron) ([S|P]):$1 Det $2:g;
 s:(iga_sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(iga#sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(iga#sugune\") A ([S|P]):$1 Pron Indef $2:g;
 s:(iga_.ks\" Pron) ([S|P]):$1 Det $2:g;
 s:(iga#.ks\" Pron) ([S|P]):$1 Det $2:g;
 s:(iga#.ks\") A ([S|P]):$1 Pron Det $2:g;
 s:(ise\" Pron) ([S|P]):$1 Pos Det Refl $2:g;
 s:(ise_enese\" Pron) ([S|P]):$1 Refl $2:g;
 s:(ise#enese\" Pron) ([S|P]):$1 Refl $2:g;
 s:(ise#enese\") A ([S|P]):$1 Pron Refl $2:g;
 s:(ise_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(ise#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(ise#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(keegi\" Pron) ([S|P]):$1 Indef $2:g;
 s:(kes\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(kumb\" Pron) ([S|P]):$1 Rel $2:g;
 s:(kumbki\" Pron) ([S|P]):$1 Det $2:g;
 s:(kõik\" Pron) ([S|P]):$1 Det $2:g;
 s:(k.ik\" Pron) ([S|P]):$1 Det $2:g;
 s:(meie\" Pron) ([S|P]):$1 Pers Ps1 $2:g;
 s:(meie_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(meie#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(meie#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(meie_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(meie#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(meie#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(mihuke\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(mihukene\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(mille_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mille#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mille#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(milline\" Pron) ([S|P]):$1 Rel $2:g;
 s:(milli=ne\" Pron) ([S|P]):$1 Rel $2:g;
 s:(mina\" Pron) ([E|S|P]):$1 Pers Ps1 $2:g;
 s:(\"ma\" Pron) ([S|P]):$1 Pers Ps1 $2:g;
 s:(minakene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mina=kene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(minake\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mina=ke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mingi\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mingi_sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mingi#sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mingi#sugune\") A ([S|P]):$1 Pron Indef $2:g;
 s:(minu_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(minu#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(minu#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(minu_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(minu#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(minu#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(miski\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mis\" Pron) ([S|P]):$1 Interr Rel $2:g; 
 s:(mis_sugune\" Pron) ([S|P]):$1 Interr Rel $2:g; 
 s:(mis#sugune\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(mis#sugune\") A ([S|P]):$1 Pron Interr Rel $2:g;
 s:(miski\" Pron) ([S|P]):$1 Interr Rel $2:g; 
 s:(miski_sugune\" Pron) ([S|P]):$1 Interr Rel $2:g; 
 s:(miski#sugune\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(miski#sugune\") A ([S|P]):$1 Pron Interr Rel $2:g;
 s:(misuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(misu=ke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(misukene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(misu=kene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(mitme_sugune\" Pron) ([S|P]):$1 Indef $2:g; 
 s:(mitme#sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mitme#sugune\") A ([S|P]):$1 Pron Indef $2:g;
 s:(mitme_taoline\" Pron) ([S|P]):$1 Indef $2:g; 
 s:(mitme#taoline\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mitme#taoline\") A ([S|P]):$1 Pron Indef $2:g;
 s:(mitmendik\" Pron) ([S|P]):$1 Interr Rel $2:g; 
 s:(mitmes\" Pron) ([S|P]):$1 Interr Rel Indef $2:g; 
 s:(mitu\" Pron) ([S|P]):$1 Indef $2:g;
 s:(mi=tu\" Pron) ([S|P]):$1 Indef $2:g;
 s:(miuke\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(miukene\" Pron) ([S|P]):$1 Interr Rel $2:g;
 s:(muist\" Pron) :$1 Indef :g;
 s:(muu\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.lema\" Pron) ([S|P]):$1 Det $2:g;
 s:(m.ne_sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.ne#sugune\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.ne#sugune\") A ([S|P]):$1 Pron Indef $2:g;
 s:(m.ni\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.ningane\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.ningas\" Pron) ([S|P]):$1 Indef $2:g;
 s:(m.herdune\" Pron) ([S|P]):$1 inder Rel $2:g;
 s:(määntne\" Pron) ([S|P]):$1 Dem $2:g; 
 s:(naa_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(naa#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(naa#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(nemad\" Pron) ([S|P]):$1 Pers Ps3 $2:g;
 s:(nende_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nende#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nende#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(nende_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nende#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nende#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(nihuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nihukene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nii_mitu\" Pron) ([S|P]):$1 Indef Interr Rel $2:g;
 s:(nii#mitu\" Pron) ([S|P]):$1 Indef Interr Rel $2:g;
 s:(nii#mitu\") A ([S|P]):$1 Pron Indef Interr Rel $2:g;
 s:(nii_mi=tu\" Pron) ([S|P]):$1 Indef Interr Rel $2:g;
 s:(nii_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nii#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nii#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(niisama_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(niisama#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(niisama#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(niisuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nisuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nisu=ke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nisukene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(nisu=kene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(niuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(niukene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(oma\" Pron) ([S|P]):$1 Pos Det Refl $2:g;
 s:(oma_enese\" Pron) ([S|P]):$1 Pos $2:g;
 s:(oma#enese\" Pron) ([S|P]):$1 Pos $2:g;
 s:(oma#enese\") A ([S|P]):$1 Pron Pos $2:g;
 s:(oma_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(oma#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(oma#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(oma_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(oma#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(oma#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(palju\" Pron) ([S|P]):$1 Indef $2:g;
 s:(sama\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sama_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sama#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sama#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(sama_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sama#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sama#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(samune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see_sama\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sama\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sama\") A ([S|P]):$1 Pron Dem $2:g;
 s:(see_samane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#samane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#samane\") A ([S|P]):$1 Pron Dem $2:g;
 s:(see_samune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#samune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#samune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(see_sinane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sinane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sinane\") A ([S|P]):$1 Pron Dem $2:g;
 s:(see_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(see#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(selle_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(selle#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(selle#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(selline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(selli=ne\" Pron) ([S|P]):$1 Dem $2:g;
 s:(setu\" Pron) ([S|P]):$1 Indef $2:g;
 s:(setmes\" Pron) ([S|P]):$1 Indef $2:g;
 s:(sihuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sihuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sina\" Pron) ([E|S|P]):$1 Pers Ps2 $2:g;
 s:(\"sa\" Pron) ([S|P]):$1 Pers Ps2 $2:g;
 s:(sinu_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sinu#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sinu#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(sinu_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sinu#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(sinu#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(siuke\" Pron) ([S|P]):$1 Dem $2:g;
 s:(siukene\" Pron) ([S|P]):$1 Dem $2:g;
 s:(säherdune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(s.herdune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(säärane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(s..rane\" Pron) ([S|P]):$1 Dem $2:g;
 s:(taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teie\" Pron) ([S|P]):$1 Pers Ps2 $2:g;
 s:(teie_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teie#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teie#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(teie_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teie#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teie#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(teine\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teine_teise\" Pron) ([S|P]):$1 Recipr $2:g;
 s:(teine#teise\" Pron) ([S|P]):$1 Recipr $2:g;
 s:(teine#teise\") A ([S|P]):$1 Pron Recipr $2:g;
 s:(teis_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teis#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teis#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(teist_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teist#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(teist#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(tema\" Pron) ([E|S|P]):$1 Pers Ps3 $2:g;
 s:(\"ta\" Pron) ([S|P]):$1 Pers Ps3 $2:g;
 s:(temake\" Pron) ([S|P]):$1 Pers Ps3 $2:g;
 s:(temakene\" Pron) ([S|P]):$1 Pers Ps3 $2:g;
 s:(tema_sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(tema#sugune\" Pron) ([S|P]):$1 Dem $2:g;
 s:(tema#sugune\") A ([S|P]):$1 Pron Dem $2:g;
 s:(tema_taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(tema#taoline\" Pron) ([S|P]):$1 Dem $2:g;
 s:(tema#taoline\") A ([S|P]):$1 Pron Dem $2:g;
 s:(too\" Pron) ([S|P]):$1 Dem $2:g;
 s:(too_sama\" Pron) ([S|P]):$1 Dem $2:g;
 s:(too#sama\" Pron) ([S|P]):$1 Dem $2:g;
 s:(too#sama\") A ([S|P]):$1 Pron Dem $2:g;
 s:(üks\" Pron) ([S|P]):$1 Dem Indef $2:g;
 s:(.ks\" Pron) ([S|P]):$1 Dem Indef $2:g;
 s:(ükski\" Pron) ([S|P]):$1 Dem Indef $2:g;
 s:(.kski\" Pron) ([S|P]):$1 Dem Indef $2:g;
 s:(.ks_teise\" Pron) ([S|P]):$1 Recipr $2:g;
 s:(üks_teise\" Pron) ([S|P]):$1 Recipr Indef $2:g;
 s:(üks#teise\" Pron) ([S|P]):$1 Recipr Indef $2:g;
 s:(üks#teise\") A ([S|P]):$1 Pron Recipr Indef $2:g;

 #s:\"(.*)ma\" V (.*)$:\"$1ma\" V $2\"$1\" :g;

 s: Adp Post : Po :g;
 s: Adp Pre : Pr :g;

 s:"\." \?:"\." Punct:g;
 s:"," \?:"," Punct:g;
 s:"!" \?:"!" Punct:g;
 s:"\?" \?:"\?" Punct:g;
 s:"\:" \?:"\:" Punct:g;
 s:";" \?:";" Punct:g;
 s:"\(" \?:"\(" Punct:g;
 s:"\)" \?:"\)" Punct:g;
 s:"\"" \?:"\"" Punct:g;
 s:"«" \?:"«" Punct:g;
 s:"»" \?:"»" Punct:g;
 s:"“" \?:"“" Punct:g;
 s:"”" \?:"”" Punct:g;
 s:"-" \?:"-" Punct:g;
 s:"¶" \?:"¶" Punct:g;

 s:"(.+)" \?:"$1" N Prop \?:g; # - guess
 s:\* ([^D]+) Der:\* Der:g; # remove 'Sg Gen' from '"koht" N* Sg Gen Der/lik A Pl Gen'
 s:"(.+)-" (.*)$:"$1-" $2 *- :g; 
 s: <([^ <>]+)>: \*$1:g; # replace <Tags> by *Tags

 print;
}


