template = "https://github.com/giellalt/template-lang-und"
rev_id = 300
template_sha = "0371712ab0950051a69847be792b3ad6c2a463ac"

[replacements]
__GLOTTOLOG_ID__ = "esto1258"
__REPO__ = "lang-est-x-utee"
__UND2C__ = "et"
__UNDEFINED__ = "Estonian"
__UND__ = "est"
