template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "esto1258"
__REPO__ = "lang-est-x-utee"
__UND2C__ = "et"
__UNDEFINED__ = "Estonian"
__UND__ = "est"
