template = "https://github.com/giellalt/template-lang-und"
rev_id = 308
template_sha = "ec3d8dc80df568320da1b4f5034d7f589ea9f666"

[replacements]
__GLOTTOLOG_ID__ = "esto1258"
__REPO__ = "lang-est-x-utee"
__UND2C__ = "et"
__UNDEFINED__ = "Estonian"
__UND__ = "est"
